# Generated by Django 6.1.1 on 2026-09-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
